
SHOTODOL_ROUTER_CSOURCES=$(wildcard $(SHOTODOL_NET_HOME)/libs/router/vsrc/*.c)
SHOTODOL_ROUTER_VSOURCE_BASE=$(basename $(notdir $(SHOTODOL_ROUTER_CSOURCES)))
OBJECTS+=$(addprefix $(SHOTODOL_NET_HOME)/$(OBJDIR_COMMON)/, $(addsuffix .o,$(SHOTODOL_ROUTER_VSOURCE_BASE)))

