
SHOTODOL_DISTRIBUTEDIO_CSOURCES=$(wildcard $(SHOTODOL_NET_HOME)/libs/distributedio/vsrc/*.c)
SHOTODOL_DISTRIBUTEDIO_VSOURCE_BASE=$(basename $(notdir $(SHOTODOL_DISTRIBUTEDIO_CSOURCES)))
OBJECTS+=$(addprefix $(SHOTODOL_NET_HOME)/$(OBJDIR_COMMON)/, $(addsuffix .o,$(SHOTODOL_DISTRIBUTEDIO_VSOURCE_BASE)))

